### ISSUE TITLE
Loop skipping incorrect.

### ISSUE THREAD

**Issue by rdebath** [AlexBoyle/BrainF-ckInterpreter#1]
BF Source; https://raw.githubusercontent.com/rdebath/Brainfuck/master/bitwidth.b
Expected result. `Hello World! 255`

I think your `findEnd` routine isn't getting the right spot when you're skipping nested loops.

**Comment by AlexBoyle** [comment]
Thank you for finding this, the issue was with my pointers being all over the place. I was starting my `findend` check one char past where I should have.

Looks like its printing `Hello World! 255` now
